name       : python-fastjsonschema
version    : 2.15.3
release    : 1
source     :
    - https://github.com/horejsek/python-fastjsonschema/archive/refs/tags/v2.15.3.tar.gz : 94e59a36c0efbf75a1a790fed15b51c9876b81204a5184c0c89075c68b10e7ec
license    : BSD-3-Clause
component  : programming.python
summary    : Fast JSON schema validator for Python
description: |
    fastjsonschema implements validation of JSON documents by JSON schema. The library implements JSON schema drafts 04, 06 and 07. The main purpose is to have a really fast implementation.   
builddeps  :
    - python-pytest-benchmark
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
