name       : python-fastjsonschema
version    : 2.16.2
release    : 3
source     :
    - https://github.com/horejsek/python-fastjsonschema/archive/refs/tags/v2.16.2.tar.gz : 552e8b07a076f4628e9a3c78f040ed673bed9b5b860d3cb51b323da50e2e3d47
homepage   : https://github.com/horejsek/python-fastjsonschema
license    : BSD-3-Clause
component  : programming.python
summary    : Fast JSON schema validator for Python
description: |
    fastjsonschema implements validation of JSON documents by JSON schema. The library implements JSON schema drafts 04, 06 and 07. The main purpose is to have a really fast implementation.   
builddeps  :
    - python-pytest-benchmark
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
